services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    ports:
      - "8000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    depends_on:
      - postgres
    tty: true
    ports:
      - "7869:11434" # Adjust based on Ollama's API port
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/vector_db
      OLLAMA_NUM_PARALLEL: 4
      OLLAMA_FLASH_ATTENTION: 1
    volumes:
      - ollama_data:/data
    networks:
      - ollama-docker
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['1', '2']
                  capabilities: [gpu]

  dev-container:
    build:
      context: .
      dockerfile: ./dev-container.dockerfile
    container_name: dev-container
    networks:
      - ollama-docker
    depends_on:
      - postgres
      - ollama
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/vector_db
      OLLAMA_URL: http://ollama:11434
    volumes:
      - ./src/:/workspace/src
    tty: true

volumes:
  postgres_data:
  ollama_data:

networks:
  ollama-docker:
    external: false
